#!/usr/bin/python2

class ClusterData:
    # ----------------- THE DATA! ---------------------
    # This static data will be replaced when the backend for the platform is created.
    # Arrays could still be used for all of the static data about machines, ex serial numbers or number of cores
    # Data Streams/Buffers would be implemented for the dynamic data.
    # The backend could also handle some of the indentification items that the front end currently addresses... maybe.


    # state:
    # 0 -      green = GOOD
    # 1 -        red = BAD
    # 2 -     yellow = WARNING/CAUTION
    # 3 - greyed out = MISSING

                  # [ [ machine name, rack#, state,[ [ blade/amm/switch/mediaTray, state, [ cpuRate, memRate, rx, tx ], [Tooltip data ] ],
    topographData = [ [ 'BLADE CENTER\n006', 1, 0, [ [ '71', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '72', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '73', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '74', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '75', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '76', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '77', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '78', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '79', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '80', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '81', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '82', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '83', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '84', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   71, 84 ],
                      [ 'BLADE CENTER\n005', 1, 1, [ [ '57', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '58', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '59', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '60', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '61', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '62', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '63', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '64', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '65', 3, [ 0, 0, '--KB', '--KB' ], ['HARDWARE MISSING'] ],
                                                     [ '66', 3, [ 0, 0, '--KB', '--KB' ], ['HARDWARE MISSING'] ],
                                                     [ '67', 3, [ 0, 0, '--KB', '--KB' ], ['HARDWARE MISSING'] ],
                                                     [ '68', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '69', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '70', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   57, 70 ],
                      [ 'BLADE CENTER\n004', 1, 0, [ [ '43', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '44', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '45', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '46', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '47', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '48', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '49', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '50', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '51', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '52', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '53', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '54', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '55', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '56', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   43, 56 ], 
                      [ 'BLADE CENTER\n003', 1, 1, [ [ '29', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '30', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '31', 0, [ 100, 10, '75KB', '25KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '32', 0, [ 100, 10, '60KB', '36KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '33', 0, [ 100, 10, '45KB', '84KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '34', 0, [ 100, 10, '56KB', '90KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '35', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '36', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '37', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '38', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '39', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '40', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '41', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '42', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 1, [], ['ON', 'PING-ABLE', 'SSH-ABLE', '3 ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 1, [], ['ON', 'PING-ABLE', 'SSH-ABLE', '4 ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   29, 42 ], 
                      [ 'BLADE CENTER\n002', 1, 0, [ [ '15', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '16', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '17', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '18', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '19', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '20', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '21', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '22', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '23', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '24', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '25', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '26', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '27', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '28', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   15, 28 ], 
                      [ 'BLADE CENTER\n001', 1, 1, [ [ '1', 1, [ 10, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '3 ERRORS', '3 CONFIG FAULTS'] ],
                                                     [ '2', 1, [ 3, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '3 ERRORS'] ],
                                                     [ '3', 1, [ 7, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '2 ERRORS'] ],
                                                     [ '4', 1, [ 21, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '6 ERRORS', '1 CONFIG FAULTS'] ],
                                                     [ '5', 1, [ 25, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '2 ERRORS'] ],
                                                     [ '6', 1, [ 3, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '3 ERRORS', '2 CONFIG FAULTS'] ],
                                                     [ '7', 1, [ 35, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '5 ERRORS'] ],
                                                     [ '8', 1, [ 32, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '5 ERRORS'] ],
                                                     [ '9', 1, [ 0, 0, '--KB', '--KB' ], ['ON', 'NOT PING-ABLE', 'NOT SSH-ABLE', '7 ERRORS'] ],
                                                     [ '10', 1, [ 0, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '2 ERRORS'] ],
                                                     [ '11', 1, [ 0, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '3 ERRORS'] ],
                                                     [ '12', 1, [ 0, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '6 ERRORS'] ],
                                                     [ '13', 1, [ 0, 0, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '3 ERRORS'] ],
                                                     [ '14', 1, [ 100, 10, '--KB', '--KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', '4 ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 1, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', '2 ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   1, 14 ],
                      [ 'BLADE CENTER\n012', 2, 0, [ [ '155', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '156', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '157', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '158', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '159', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '160', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '161', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '162', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '163', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '164', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '165', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '166', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '167', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '168', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   155, 168 ],
                      [ 'BLADE CENTER\n011', 2, 0, [ [ '141', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '142', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '143', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '144', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '145', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '146', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '147', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '148', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '149', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '150', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '151', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '152', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '153', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '154', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   141, 154 ],
                      [ 'BLADE CENTER\n010', 2, 0, [ [ '127', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '128', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '129', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '130', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '131', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '132', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '133', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '134', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '135', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '136', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '137', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '138', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '139', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '140', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   127, 140 ],
                      [ 'BLADE CENTER\n009', 2, 1, [ [ '113', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '114', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '115', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '116', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '117', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '118', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '119', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '120', 1, [ 0, 0, '--KB', '--KB' ], ['OFF'] ],
                                                     [ '121', 1, [ 0, 0, '--KB', '--KB' ], ['OFF'] ],
                                                     [ '122', 1, [ 0, 0, '--KB', '--KB' ], ['OFF'] ],
                                                     [ '123', 1, [ 0, 0, '--KB', '--KB' ], ['OFF'] ],
                                                     [ '124', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '125', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '126', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   113, 126 ],
                      [ 'BLADE CENTER\n008', 2, 0, [ [ '99', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '100', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '101', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '102', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '103', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '104', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '105', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '106', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '107', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '108', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '109', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '110', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '111', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '112', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   99, 112 ],
                      [ 'BLADE CENTER\n007', 2, 0, [ [ '85', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '86', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '87', 0, [ 100, 91, '105KB', '99KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '88', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '89', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '90', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '91', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '92', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '93', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '94', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '95', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '96', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '97', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '98', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   85, 98 ],
                      [ 'BLADE CENTER\n018', 3, 0, [ [ '239', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '240', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '241', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '242', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '243', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '244', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '245', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '246', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '247', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '248', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '249', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '250', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '251', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '252', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   239, 252 ],
                      [ 'BLADE CENTER\n017', 3, 0, [ [ '225', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '226', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '227', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '228', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '229', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '230', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '231', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '232', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '233', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '234', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '235', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '236', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '237', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '238', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   225, 238 ],
                      [ 'BLADE CENTER\n016', 3, 0, [ [ '211', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '212', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '213', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '214', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '215', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '216', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '217', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '218', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '219', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '220', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '221', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '222', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '223', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '224', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   211, 224 ],
                      [ 'BLADE CENTER\n015', 3, 0, [ [ '197', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '198', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '199', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '200', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '201', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '202', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '203', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '204', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '205', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '206', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '207', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '208', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '209', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '210', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   197, 210 ],
                      [ 'BLADE CENTER\n014', 3, 0, [ [ '183', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '184', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '185', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '186', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '187', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '188', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '189', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '190', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '191', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '192', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '193', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '194', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '195', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '196', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   183, 196 ],
                      [ 'BLADE CENTER\n013', 3, 0, [ [ '169', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '170', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '171', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '172', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '173', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '174', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '175', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '176', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '177', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '178', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '179', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '180', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '181', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ '182', 0, [ 100, 10, '85KB', '100KB' ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'ADVANCED\nMANAGEMENT\nMODULE', 0, [ ], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n001', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'SWITCH\nMODULE\n002', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ],
                                                     [ 'MEDIA\nTRAY', 0, [], ['ON', 'PING-ABLE', 'SSH-ABLE', 'NO ERRORS'] ] ],
                                                   169, 182 ] ]

    managementNodeData = [ [ 'LCCA\nHEAD\nNODE', 0, [] ],
                           [ 'CLUSTER\nMANAGEMENT\nNODE', 0, [] ] ]
